# Generated by Django 5.2.4 on 2025-08-02 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Telefone')),
                ('date_birth', models.DateField(verbose_name='Data de nascimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
