# Generated by Django 5.2.4 on 2025-08-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='service.category', verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
