# Generated by Django 5.2.4 on 2025-08-05 20:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_date_birth'),
        ('service', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_atendimento', 'Em atendimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='Status')),
                ('date_schedule', models.DateField(verbose_name='Data do agendamento')),
                ('time_schedule', models.TimeField(verbose_name='Hora do agendamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Cliente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.profissional', verbose_name='Profissional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Serviço')),
            ],
        ),
    ]
